# Importing the notecessary Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import pylab as pl
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline

# Importing the Datasets

In [2]:
#url='C:\Users\Home\Downloads'
df = pd.read_csv(r"C:\Users\Home\Downloads/energydata_complete.csv")
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,1/11/2016 17:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.60,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,1/11/2016 17:10,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.48,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,1/11/2016 17:20,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.37,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,1/11/2016 17:30,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.25,733.8,92.0,6.000000,51.500000,5.0,45.410390,45.410390
4,1/11/2016 17:40,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.13,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [3]:
# lets drop the 'date' and 'light' columns
df.drop(columns=['date','lights'], inplace=True)
df.head(3)

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.53,6.60,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.56,6.48,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,50,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.50,6.37,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668

# Data Pre-processing

In [4]:
# Applying MinMaxScaler to scale the features column 

from sklearn.preprocessing import MinMaxScaler

# lets instantiate the scaler
scaler = MinMaxScaler()

# lets normmalize the features using the MinMaxScaler
normalized_features = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

In [122]:
# splitting data into features(independent) and target(dependent) variables

# predictors
features = normalized_features.drop(['Appliances'], axis=1)

# target variable
target = normalized_features['Appliances']

In [123]:
# splitting data into training and testing set

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(features, target, test_size = 0.3, random_state = 42)


print(f'shape of training set is {x_train.shape}')
print(f'shape of testing set is {x_test.shape}')

shape of training set is (13814, 26)
shape of testing set is (5921, 26)

# Modeling

In [131]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
#fit the model to the training dataset
regressor.fit(x_train, y_train)

#obtain predictions
Y_pred = regressor.predict(x_test)


for coef, col in enumerate(x_train.columns):
    print(f'{col}:  {regressor.coef_[coef]}')

T1:  -0.003241639288365497
RH_1:  0.5535164310819514
T2:  -0.2361982416077288
RH_2:  -0.4566620664104151
T3:  0.29058675715614213
RH_3:  0.09609468510013987
T4:  0.028957001081334817
RH_4:  0.026370352972229994
T5:  -0.015645161762984763
RH_5:  0.016009014240253968
T6:  0.23644072986309103
RH_6:  0.038022667433710515
T7:  0.010349769958096002
RH_7:  -0.04461979916132822
T8:  0.10199549423546236
RH_8:  -0.15758506050032098
T9:  -0.18997749134205033
RH_9:  -0.03980848103847861
T_out:  -0.3219685723513081
Press_mm_hg:  0.006832060976464997
RH_out:  -0.07774847768909361
Windspeed:  0.02917819430351639
Visibility:  0.012305820227760115
Tdewpoint:  0.11786204360759457
rv1:  0.0007651678571257345
rv2:  0.0007651678571257345

# Model Evaluation

In [125]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, Y_pred)
print(f'Mean_absolute_error: {round(mae, 3)}')

Mean_absolute_error: 0.05

In [108]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, Y_pred)
print(f'r2_score: {round(r2_score, 3)}')

r2_score: 0.149

In [109]:
import numpy as np
rss = np.sum(np.square(y_test - Y_pred))
print(f'Residual_sum_of_squares: {round(rss, 3)}')

Residual_sum_of_squares: 45.348

In [114]:
from sklearn.metrics import  mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, Y_pred))
print(f'root_Mean_squared_error: {round(rmse, 9)}')

root_Mean_squared_error: 0.087515253

### Lasso Regression and feature selection

In [130]:
from sklearn.metrics import r2_score
from sklearn.linear_model import Lasso

lasso_reg = Lasso(alpha=0.001)

lasso_reg.fit(x_train, y_train)

y_predicted = lasso_reg.predict(x_test)

#lasso_r2_ = lasso_reg.score(y_test, y_predicted)
lasso_r2 = r2_score(y_test, y_predicted)
#lasso_r2
RMSE = np.sqrt(mean_squared_error(y_test, y_predicted))
round(RMSE,3)

0.094

In [128]:
for coef, col in enumerate(x_train.columns):
    print(f'{col}:  {lasso_reg.coef_[coef]}')

T1:  0.0
RH_1:  0.01787993166800193
T2:  0.0
RH_2:  -0.0
T3:  0.0
RH_3:  0.0
T4:  -0.0
RH_4:  0.0
T5:  -0.0
RH_5:  0.0
T6:  0.0
RH_6:  -0.0
T7:  -0.0
RH_7:  -0.0
T8:  0.0
RH_8:  -0.00011003649556417199
T9:  -0.0
RH_9:  -0.0
T_out:  0.0
Press_mm_hg:  -0.0
RH_out:  -0.04955749437720922
Windspeed:  0.00291176479259292
Visibility:  0.0
Tdewpoint:  0.0
rv1:  -0.0
rv2:  -0.0

### 4 coefficient had non-zero values

### Ridge Regression

In [112]:
from sklearn.metrics import  mean_squared_error
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)

ridge_reg.fit(x_train, y_train)

y_predicted = ridge_reg.predict(x_test)

#lasso_r2_ = lasso_reg.score(y_test, y_predicted)
ridge_r2 = r2_score(y_test, y_predicted)
RMSE = np.sqrt(mean_squared_error(y_test, y_predicted))
RMSE

0.08753457737387427

#### get the weights of regularization

In [132]:
#comparing the effects of regularisation
def get_weights_df(model, feat, col_name):
  #this function returns the weight of every feature
  weights = pd.Series(model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

linear_model_weights = get_weights_df(regressor, x_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')


final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')
final_weights

       Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456662     -0.411048     -0.000000
1         T_out            -0.321969     -0.262343      0.000000
2            T2            -0.236198     -0.201417      0.000000
3            T9            -0.189977     -0.188948     -0.000000
4          RH_8            -0.157585     -0.156818     -0.000110
5        RH_out            -0.077748     -0.054822     -0.049557
6          RH_7            -0.044620     -0.045983     -0.000000
7          RH_9            -0.039808     -0.041373     -0.000000
8            T5            -0.015645     -0.019840     -0.000000
9            T1            -0.003242     -0.018372      0.000000
10          rv1             0.000765      0.000744     -0.000000
11          rv2             0.000765      0.000744     -0.000000
12  Press_mm_hg             0.006832      0.006578     -0.000000
13           T7             0.010350      0.010126     -0.000000
14   Visibility             0.012306      0.012076      0.000000
15         RH_5             0.016009      0.016154      0.000000
16         RH_4             0.026370      0.024565      0.000000
17           T4             0.028957      0.027364     -0.000000
18    Windspeed             0.029178      0.030262      0.002912
19         RH_6             0.038023      0.035500     -0.000000
20         RH_3             0.096095      0.095173      0.000000
21           T8             0.101995      0.101028      0.000000
22    Tdewpoint             0.117862      0.083261      0.000000
23           T6             0.236441      0.217324      0.000000
24           T3             0.290587      0.288055      0.000000
25         RH_1             0.553516      0.519502      0.017880

In [138]:

lowest_feature_weight=final_weights.loc[(final_weights['Linear_Model_Weight'])==(final_weights['Linear_Model_Weight'].min())][['Features','Linear_Model_Weight']]


highest_feature_weight=final_weights.loc[(final_weights['Linear_Model_Weight'])==(final_weights['Linear_Model_Weight'].max())][['Features','Linear_Model_Weight']]
print(f'lowest_feature_weight:{lowest_feature_weight}\n')

print(f'highest_feature_weight:{highest_feature_weight}')

lowest_feature_weight:  Features  Linear_Model_Weight
0     RH_2            -0.456662

highest_feature_weight:   Features  Linear_Model_Weight
25     RH_1             0.553516

# Fitting a linear_model on the relationship T2 and T6

In [18]:
normalized_features.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369132,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365595,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357878,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [90]:
X = normalized_features['T2'].values.reshape(-1,1)
Y = normalized_features['T6'].values.reshape(-1,1)

In [82]:
regressor.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [92]:
regressor.score(X,Y)

0.6418957425670084

In [93]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.3, random_state=42)

In [139]:
from sklearn.metrics import r2_score
regressor.fit(X_train,Y_train)

y_pred = regressor.predict(X_test)

# r2_score = regressor.score(X_train,Y_train)




mae = mean_absolute_error(Y_test, y_pred)
print(f'MAE: {round(mae, 3)}') 

mse = mean_squared_error(Y_test, y_pred)
print(f'MSE: {round(mse, 3)}') 

rmse = np.sqrt(mean_squared_error(Y_test, y_pred))
print(f'RMSE: {round(rmse, 3)}') 
 

r2_score = r2_score(Y_test, y_pred)
print(f'r2_score: {round(r2_score, 3)}')

MAE: 0.082
MSE: 0.011
RMSE: 0.106
r2_score: 0.643

In [140]:
rss = np.sum(np.square(Y_test - y_pred))
print(f'RSS: {round(rss, 2)}')

RSS: 66.12